### ISSUE TITLE
cannot overrides the arrow styles

### ISSUE THREAD

**Issue by zourdyzou** [statuspal/badge#1]
Hi Statuspal team!

I am trying to style the tooltip status and actually wanted to overwrite the arrow styles (so it won't show up) and I tried to wipe the content in the pseudo-element but it didn't work

```css
  ::after {
         content: none;
         border-style: none;
   }
```

I am using CSS modules and the base `status body message` overwrites is working just fine.

**Comment by messutied** [comment]
Hi there,

You just need to use this instead:

```css
.sp-tooltip--top::after { display: none; }
```

This if you're using the tooltip displayed at the top, which is the default, else replace `--top` with `--bottom` or `--left` or `--right`.
